import { useCallback, useEffect, useState } from "react";

import {
  acknowledgeProviderDisclosure,
  getProviderDisclosure,
} from "../api/provider";
import type { ProviderDisclosure as Disclosure } from "../api/provider";
import "./ProviderDisclosure.css";

type ProviderDisclosureGateProps = {
  children: React.ReactNode;
};

/**
 * T051 (US6/FR-014, SC-007): the first-run disclosure screen, gating the upload surface.
 *
 * The server enforces the same rule — `submit_uploads` refuses with 409
 * `disclosure_not_acknowledged` until the workspace records an ack — so this screen is the UI half,
 * not the guard itself. It deliberately *fails closed*: if the disclosure cannot be read, uploads
 * stay hidden rather than being offered and then refused. It gates only the source-library page, not
 * the whole shell, because asking questions and reading decisions never send document text.
 */
export function ProviderDisclosureGate({ children }: ProviderDisclosureGateProps) {
  const [disclosure, setDisclosure] = useState<Disclosure | null>(null);
  const [status, setStatus] = useState<"loading" | "ready" | "error">("loading");
  const [error, setError] = useState<string | null>(null);
  const [acknowledging, setAcknowledging] = useState(false);

  const load = useCallback(async () => {
    setStatus("loading");
    try {
      setDisclosure(await getProviderDisclosure());
      setError(null);
      setStatus("ready");
    } catch (caught) {
      setError(
        caught instanceof Error ? caught.message : "The disclosure could not be read.",
      );
      setStatus("error");
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  const acknowledge = async () => {
    setAcknowledging(true);
    setError(null);
    try {
      setDisclosure(await acknowledgeProviderDisclosure());
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : "The disclosure could not be acknowledged.",
      );
    } finally {
      setAcknowledging(false);
    }
  };

  if (status === "ready" && disclosure?.acknowledged_at) {
    return <>{children}</>;
  }

  if (status === "loading") {
    return (
      <section className="page-intro" aria-live="polite">
        <p className="eyebrow">Before you upload</p>
        <h1>Checking what this install shares…</h1>
      </section>
    );
  }

  if (status === "error" || !disclosure) {
    return (
      <section className="page-intro" aria-labelledby="provider-disclosure-title">
        <p className="eyebrow">Uploads paused</p>
        <h1 id="provider-disclosure-title">The data-handling disclosure could not be read</h1>
        <p className="page-description">
          Uploads stay unavailable until the active provider is known — this install discloses where
          document text goes before it accepts any.
        </p>
        <p className="provider-disclosure__error" role="alert">
          {error ?? "The disclosure could not be read."}
        </p>
        <div className="provider-disclosure__actions">
          <button type="button" onClick={() => void load()}>
            Try again
          </button>
        </div>
      </section>
    );
  }

  const remote = disclosure.sends_document_text_remotely;
  const generation = disclosure.generation_provider;
  const embedding = disclosure.embedding_provider;
  const generationRemote = disclosure.generation_sends_document_text_remotely;
  const embeddingRemote = disclosure.embedding_sends_document_text_remotely;
  return (
    <section className="page-intro" aria-labelledby="provider-disclosure-title">
      <p className="eyebrow">Before you upload</p>
      <h1 id="provider-disclosure-title">Where your documents go</h1>
      <p className="page-description">
        {remote ? (
          <strong>Document text leaves this machine.</strong>
        ) : (
          <strong>Document text stays on this machine.</strong>
        )}{" "}
        Nothing else about this install is transmitted.
      </p>
      <ul className="provider-disclosure__facts">
        <li>
          <span className="provider-disclosure__marker" aria-hidden="true" />
          <span>
            {embeddingRemote ? (
              <>
                The search index is built by <strong>{embedding}</strong>. Text you upload is sent
                to {embedding}&rsquo;s service to build it.
              </>
            ) : (
              <>
                The search index is built by <strong>{embedding}</strong>, which runs on this
                machine.
              </>
            )}
          </span>
        </li>
        <li>
          <span className="provider-disclosure__marker" aria-hidden="true" />
          <span>
            {generationRemote ? (
              <>
                Answers are generated by <strong>{generation}</strong>. Text you upload is sent to{" "}
                {generation}&rsquo;s service to generate them.
              </>
            ) : (
              <>
                Answers are generated by <strong>{generation}</strong>, which runs on this machine.
              </>
            )}
          </span>
        </li>
        <li>
          <span className="provider-disclosure__marker" aria-hidden="true" />
          <span>
            You can change the provider later in Account &rarr; Model provider. A change that alters
            the embedding profile re-ingests every document in this workspace.
          </span>
        </li>
      </ul>
      {error && (
        <p className="provider-disclosure__error" role="alert">
          {error}
        </p>
      )}
      <div className="provider-disclosure__actions">
        <button type="button" onClick={() => void acknowledge()} disabled={acknowledging}>
          {acknowledging ? "Recording acknowledgement…" : "I understand — continue"}
        </button>
        <span>Uploads are refused until you acknowledge this.</span>
      </div>
    </section>
  );
}
