/**
 * T051 (US6/FR-014, SC-007): the provider-disclosure screen that gates the upload surface.
 *
 * The tests pin the three things this screen is responsible for: naming the active provider and
 * stating plainly whether document text leaves the machine, revealing the library only after the ack
 * is recorded server-side, and failing closed when the disclosure cannot be read — an upload offered
 * and then refused with 409 is exactly the state FR-014 exists to prevent.
 */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, it, vi } from "vitest";

import {
  acknowledgeProviderDisclosure,
  getProviderDisclosure,
} from "../api/provider";
import type { ProviderDisclosure } from "../api/provider";
import { ProviderDisclosureGate } from "./ProviderDisclosure";

vi.mock("../api/provider", () => ({
  getProviderDisclosure: vi.fn(),
  acknowledgeProviderDisclosure: vi.fn(),
}));

const readDisclosure = vi.mocked(getProviderDisclosure);
const acknowledged = vi.mocked(acknowledgeProviderDisclosure);

function disclosure(overrides: Partial<ProviderDisclosure> = {}): ProviderDisclosure {
  return {
    provider: "gemini",
    generation_provider: "gemini",
    embedding_provider: "gemini",
    generation_sends_document_text_remotely: true,
    embedding_sends_document_text_remotely: true,
    sends_document_text_remotely: true,
    acknowledged_at: null,
    ...overrides,
  };
}

afterEach(() => {
  vi.clearAllMocks();
});

it("names the provider and says text leaves the machine, keeping the library hidden", async () => {
  readDisclosure.mockResolvedValue(disclosure());

  render(
    <ProviderDisclosureGate>
      <p>Source library contents</p>
    </ProviderDisclosureGate>,
  );

  expect(
    await screen.findByRole("heading", { name: /where your documents go/i }),
  ).toBeInTheDocument();
  // Same provider for both roles, so the name appears once per disclosed fact.
  expect(screen.getAllByText("gemini")).toHaveLength(2);
  expect(screen.getByText(/document text leaves this machine/i)).toBeVisible();
  // The upload surface must not be reachable before the ack.
  expect(screen.queryByText("Source library contents")).not.toBeInTheDocument();
});

it("says text stays local when every provider runs on this machine", async () => {
  readDisclosure.mockResolvedValue(
    disclosure({
      provider: "ollama",
      generation_provider: "ollama",
      embedding_provider: "ollama",
      generation_sends_document_text_remotely: false,
      embedding_sends_document_text_remotely: false,
      sends_document_text_remotely: false,
    }),
  );

  render(
    <ProviderDisclosureGate>
      <p>Source library contents</p>
    </ProviderDisclosureGate>,
  );

  expect(await screen.findByText(/document text stays on this machine/i)).toBeVisible();
  expect(screen.getAllByText(/runs on this machine/i)).toHaveLength(2);
});

it("names the correct destination in a mixed configuration (V146)", async () => {
  // Local generation + remote embedding: the search index goes to Gemini, answers stay local.
  // The bug this pins said text was "sent to ollama's service", which is wrong.
  readDisclosure.mockResolvedValue(
    disclosure({
      provider: "ollama",
      generation_provider: "ollama",
      embedding_provider: "gemini",
      generation_sends_document_text_remotely: false,
      embedding_sends_document_text_remotely: true,
      sends_document_text_remotely: true,
    }),
  );

  render(
    <ProviderDisclosureGate>
      <p>Source library contents</p>
    </ProviderDisclosureGate>,
  );

  expect(await screen.findByText(/document text leaves this machine/i)).toBeVisible();
  // The search index is built by the embedding provider, and only that text goes remote.
  expect(screen.getByText(/the search index is built by/i)).toHaveTextContent("gemini");
  expect(screen.getByText(/sent to gemini/i)).toBeVisible();
  // Answers are generated locally by the generation provider.
  expect(screen.getByText(/answers are generated by/i)).toHaveTextContent("ollama");
  expect(screen.getByText(/which runs on this machine/i)).toBeVisible();
});

it("reveals the library once the acknowledgement is recorded", async () => {
  const user = userEvent.setup();
  readDisclosure.mockResolvedValue(disclosure());
  acknowledged.mockResolvedValue(
    disclosure({ acknowledged_at: "2026-09-26T12:00:00Z" }),
  );

  render(
    <ProviderDisclosureGate>
      <p>Source library contents</p>
    </ProviderDisclosureGate>,
  );

  await user.click(
    await screen.findByRole("button", { name: /i understand/i }),
  );

  expect(acknowledged).toHaveBeenCalledTimes(1);
  expect(await screen.findByText("Source library contents")).toBeVisible();
  expect(
    screen.queryByRole("heading", { name: /where your documents go/i }),
  ).not.toBeInTheDocument();
});

it("enters straight through when the workspace already acknowledged", async () => {
  readDisclosure.mockResolvedValue(
    disclosure({ acknowledged_at: "2026-09-25T08:00:00Z" }),
  );

  render(
    <ProviderDisclosureGate>
      <p>Source library contents</p>
    </ProviderDisclosureGate>,
  );

  expect(await screen.findByText("Source library contents")).toBeVisible();
  expect(acknowledged).not.toHaveBeenCalled();
});

it("stays closed when the disclosure cannot be read, and retries on demand", async () => {
  const user = userEvent.setup();
  readDisclosure
    .mockRejectedValueOnce(new Error("The API could not be reached"))
    .mockResolvedValue(disclosure({ acknowledged_at: "2026-09-26T09:00:00Z" }));

  render(
    <ProviderDisclosureGate>
      <p>Source library contents</p>
    </ProviderDisclosureGate>,
  );

  expect(await screen.findByRole("alert")).toHaveTextContent(/could not be reached/i);
  // Fail closed: an unreachable disclosure must not silently enable uploads.
  expect(screen.queryByText("Source library contents")).not.toBeInTheDocument();

  await user.click(screen.getByRole("button", { name: /try again/i }));

  expect(await screen.findByText("Source library contents")).toBeVisible();
});
