import { type FormEvent } from "react";
import type { AnswerResponse, ConversationDetail } from "../api/types";
import { CitationList } from "./CitationList";
import { RetrievalTrace } from "./RetrievalTrace";

type Props = { conversation: ConversationDetail | null; question: string; loading: boolean; error: string | null; onQuestionChange: (question: string) => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void };

function AnswerCard({ id, response, stale }: { id: string; response: AnswerResponse; stale: boolean }) {
  const citations = new Map(response.citations.map((citation, index) => [citation.passage_id, index + 1] as const));
  return <article className="answer-card"><div className="answer-card__heading"><div><p className="eyebrow">Assistant</p><h3>Evidence-backed answer</h3></div><div className="answer-state"><strong className={`answer-state--${response.state}`}>{response.state}</strong><span>{response.confidence} confidence</span></div></div>{stale ? <p className="cached-answer-status cached-answer-status--stale">Corpus changed since this answer was generated.</p> : null}<p className="answer-text">{response.answer}</p>{response.claims.length > 0 ? <ol className="answer-claims" aria-label="Answer claims">{response.claims.map((claim, index) => <li key={`${claim.text}-${index}`}>{claim.text} {claim.passage_ids.map((passageId) => citations.get(passageId)).filter((number): number is number => number !== undefined).map((number) => <a key={number} href={`#${id}-citation-${number}`}>[{number}]</a>)}</li>)}</ol> : null}{response.conflicts.length > 0 ? <div className="conflict-warning" role="alert"><strong>Conflicting evidence</strong><span>Sources disagree about: {response.conflicts.map((conflict) => conflict.facet).join(", ")}.</span></div> : null}{response.unsupported_facets.length > 0 ? <aside className="unsupported-facets"><strong>Unsupported by current evidence</strong><ul>{response.unsupported_facets.map((facet) => <li key={facet}>{facet}</li>)}</ul></aside> : null}<CitationList citations={response.citations} idPrefix={`${id}-citation`} /><RetrievalTrace traceId={response.trace_id} /></article>;
}

export function ConversationThread({ conversation, question, loading, error, onQuestionChange, onSubmit }: Props) {
  return <section className="conversation-thread" aria-labelledby="conversation-title"><header><p className="eyebrow">Evidence-backed answers</p><h1 id="conversation-title">{conversation?.title ?? "Ask your project memory"}</h1><p className="page-description">Ask a follow-up and the saved thread resolves its context from current evidence.</p></header>{conversation?.messages.map((message) => <div className="conversation-turn" key={message.id}><section className="conversation-question"><p className="eyebrow">You</p><p>{message.question}</p></section><AnswerCard id={message.id} response={message.response} stale={message.stale} /></div>)}{error ? <div className="answer-error" role="alert"><strong>{error}</strong></div> : null}{loading ? <div className="answer-loading" role="status" aria-live="polite"><strong>Searching workspace evidence…</strong><span>Checking decisions, sources, and possible conflicts.</span><span className="answer-loading__bar" aria-hidden="true" /></div> : null}<form className="question-form" onSubmit={onSubmit}><label htmlFor="project-question">{conversation ? "Ask a follow-up" : "Start a conversation"}</label><div><textarea id="project-question" value={question} onChange={(event) => onQuestionChange(event.target.value)} placeholder="Who changed authentication? Then ask why it changed." rows={3} maxLength={2_000} /><button type="submit" disabled={loading || !question.trim()}>{loading ? "Asking…" : "Ask"}</button></div></form></section>;
}
